# Generated by Django 3.1.7 on 2021-03-25 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('detail_pk', models.IntegerField(primary_key=True, serialize=False)),
                ('detail_name', models.CharField(max_length=100)),
                ('cipher_detail', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'detail',
            },
        ),
        migrations.CreateModel(
            name='InterWorkshopRoutes',
            fields=[
                ('routes_pk', models.IntegerField(primary_key=True, serialize=False)),
                ('detail_pk', models.ForeignKey(blank=True, db_column='detail_pk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api_app.detail')),
            ],
            options={
                'db_table': 'inter_workshop_routes',
            },
        ),
        migrations.CreateModel(
            name='ProductionProgramForTheQuarterByMonth',
            fields=[
                ('production_program_quarter_pk', models.IntegerField(primary_key=True, serialize=False)),
                ('quarter_number', models.IntegerField()),
            ],
            options={
                'db_table': 'production_program_for_the_quarter_by_month',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_pk', models.IntegerField(primary_key=True, serialize=False)),
                ('doc_num', models.CharField(max_length=20)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'report',
            },
        ),
        migrations.CreateModel(
            name='UsingInstruction',
            fields=[
                ('using_pk', models.IntegerField(primary_key=True, serialize=False)),
                ('detail_manufactured_pk', models.OneToOneField(db_column='detail_manufactured_pk', on_delete=django.db.models.deletion.DO_NOTHING, to='api_app.detail')),
            ],
            options={
                'db_table': 'using_instruction',
            },
        ),
        migrations.CreateModel(
            name='Vedomost',
            fields=[
                ('vedomost_pk', models.IntegerField(primary_key=True, serialize=False)),
                ('creation_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vedomost',
            },
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('workshop_pk', models.IntegerField(primary_key=True, serialize=False)),
                ('workshop_name', models.CharField(max_length=100)),
                ('cipher_workshop', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'workshop',
            },
        ),
        migrations.CreateModel(
            name='VedomostLine',
            fields=[
                ('vedomost_line_pk', models.IntegerField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('detail_pk', models.ForeignKey(blank=True, db_column='detail_pk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api_app.detail')),
                ('vedomost_pk', models.ForeignKey(blank=True, db_column='vedomost_pk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api_app.vedomost')),
            ],
            options={
                'db_table': 'vedomost_line',
            },
        ),
        migrations.AddField(
            model_name='vedomost',
            name='workshop_pk',
            field=models.ForeignKey(blank=True, db_column='workshop_pk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api_app.workshop'),
        ),
        migrations.CreateModel(
            name='UsingLine',
            fields=[
                ('using_line_pk', models.IntegerField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('detail_pk', models.ForeignKey(blank=True, db_column='detail_pk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api_app.detail')),
                ('using_pk', models.ForeignKey(blank=True, db_column='using_pk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api_app.usinginstruction')),
            ],
            options={
                'db_table': 'using_line',
            },
        ),
        migrations.CreateModel(
            name='ReportLine',
            fields=[
                ('report_line_pk', models.IntegerField(primary_key=True, serialize=False)),
                ('produced', models.IntegerField()),
                ('detail_pk', models.ForeignKey(blank=True, db_column='detail_pk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api_app.detail')),
                ('report_pk', models.ForeignKey(blank=True, db_column='report_pk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api_app.report')),
            ],
            options={
                'db_table': 'report_line',
            },
        ),
        migrations.AddField(
            model_name='report',
            name='workshop_receiver_pk',
            field=models.ForeignKey(blank=True, db_column='workshop_receiver_pk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='report_receiver', to='api_app.workshop'),
        ),
        migrations.AddField(
            model_name='report',
            name='workshop_sender_pk',
            field=models.ForeignKey(blank=True, db_column='workshop_sender_pk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='report_sender', to='api_app.workshop'),
        ),
        migrations.CreateModel(
            name='ProductionProgramByMonth',
            fields=[
                ('production_program_pk', models.IntegerField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('creation_date', models.DateField()),
                ('workshop_pk', models.ForeignKey(db_column='workshop_pk', on_delete=django.db.models.deletion.DO_NOTHING, to='api_app.workshop')),
            ],
            options={
                'db_table': 'production_program_by_month',
                'unique_together': {('production_program_pk', 'workshop_pk')},
            },
        ),
        migrations.CreateModel(
            name='LineOfRoute',
            fields=[
                ('string_route_pk', models.IntegerField(primary_key=True, serialize=False)),
                ('details_amount', models.IntegerField()),
                ('detail_pk', models.ForeignKey(blank=True, db_column='detail_pk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api_app.detail')),
                ('routes_pk', models.ForeignKey(blank=True, db_column='routes_pk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api_app.interworkshoproutes')),
                ('workshop_receiver_pk', models.ForeignKey(blank=True, db_column='workshop_receiver_pk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='line_receiver', to='api_app.workshop')),
                ('workshop_sender_pk', models.ForeignKey(blank=True, db_column='workshop_sender_pk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='line_sender', to='api_app.workshop')),
            ],
            options={
                'db_table': 'line_of_route',
            },
        ),
        migrations.CreateModel(
            name='ProgramLine',
            fields=[
                ('program_line_pk', models.IntegerField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('detail_pk', models.ForeignKey(db_column='detail_pk', on_delete=django.db.models.deletion.DO_NOTHING, to='api_app.detail')),
                ('production_program_pk', models.ForeignKey(db_column='production_program_pk', on_delete=django.db.models.deletion.DO_NOTHING, to='api_app.productionprogrambymonth')),
            ],
            options={
                'db_table': 'program_line',
                'unique_together': {('program_line_pk', 'production_program_pk', 'detail_pk')},
            },
        ),
        migrations.CreateModel(
            name='ProductionProgramForTheQuarterByMonthLine',
            fields=[
                ('line_pk', models.IntegerField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('month_number', models.IntegerField(blank=True, null=True)),
                ('detail_pk', models.ForeignKey(db_column='detail_pk', on_delete=django.db.models.deletion.DO_NOTHING, to='api_app.detail')),
                ('production_program_quarter_pk', models.ForeignKey(db_column='production_program_quarter_pk', on_delete=django.db.models.deletion.DO_NOTHING, to='api_app.productionprogramforthequarterbymonth')),
            ],
            options={
                'db_table': 'production_program_for_the_quarter_by_month_line',
                'unique_together': {('line_pk', 'detail_pk', 'production_program_quarter_pk')},
            },
        ),
    ]
