# Generated by Django 3.1.7 on 2021-03-25 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0003_auto_20210326_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vedomost',
            name='doc_num',
            field=models.IntegerField(),
        ),
    ]
