# Generated by Django 3.1.7 on 2021-03-26 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0004_auto_20210326_0045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='workshop_receiver_pk',
        ),
        migrations.AddField(
            model_name='reportline',
            name='workshop_receiver_pk',
            field=models.ForeignKey(blank=True, db_column='workshop_receiver_pk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api_app.workshop'),
        ),
        migrations.AlterField(
            model_name='report',
            name='workshop_sender_pk',
            field=models.ForeignKey(blank=True, db_column='workshop_sender_pk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api_app.workshop'),
        ),
        migrations.AlterField(
            model_name='reportline',
            name='report_pk',
            field=models.ForeignKey(blank=True, db_column='report_pk', null=True, on_delete=django.db.models.deletion.CASCADE, to='api_app.report'),
        ),
        migrations.AlterField(
            model_name='vedomostline',
            name='vedomost_pk',
            field=models.ForeignKey(blank=True, db_column='vedomost_pk', null=True, on_delete=django.db.models.deletion.CASCADE, to='api_app.vedomost'),
        ),
    ]
