# Generated by Django 3.2 on 2021-04-08 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0005_auto_20210326_2107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vedomost',
            options={'get_latest_by': 'creation_date'},
        ),
    ]
